name: ${name}
version: ${version}
main: ${main}
load: POSTWORLD
author: "Arian"
api-version: '${apiVersion}'
softdepend: [PlaceholderAPI]
commands:
  removedurability:
    aliases:
      - "removedura"
      - "rmdurability"
      - "rmdura"
    permission: "removedurability.rm"
    usage: "/<command>"
permissions:
  removedurability.*:
    default: "op"
    children:
      ["removedurability.rm", "true"]
  removedurability:rm:
    default: "op"
