name: Bug report
description: Create a report to help improve the Project
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report! Fill out the following form to your best ability to help fix the problem.
      Only use this if you're absolutely sure that you found a bug and can reproduce it.
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: To Reproduce
    description: Steps to reproduce this behaviour
    placeholder: |
      1. Go to '...'
      2. Click on '...'
      3. Scroll down to '...'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behaviour
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots / Videos
    description: If applicable, add screenshots to help explain your problem.
- type: input
  attributes:
    label: Mod Version
    description: What version of this project are you running?
    placeholder: "For example: 1.0.0"
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context
    description: Add any other context about the problem here
